# Generated by Django 4.1.3 on 2023-05-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rule',
            field=models.IntegerField(choices=[(0, '管理员'), (1, '用户')], default=1, verbose_name='权限'),
        ),
    ]
