# Generated by Django 4.2 on 2023-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0002_alter_user_id_alter_user_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序列ID')),
                ('uid', models.IntegerField(verbose_name='用户ID')),
                ('location', models.CharField(max_length=256, verbose_name='文件路径')),
            ],
            options={
                'db_table': 'upload_record',
            },
        ),
    ]
