# Generated by Django 4.2 on 2023-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0004_uploadrecord_ctime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='任务ID')),
                ('upload_id', models.IntegerField(verbose_name='文件ID')),
                ('uid', models.IntegerField(verbose_name='用户ID')),
                ('pictures', models.TextField(verbose_name='图片列表')),
                ('status', models.IntegerField(choices=[(0, '分析中'), (1, '完成')], default=0, verbose_name='任务状态')),
            ],
            options={
                'db_table': 'analysis_record',
            },
        ),
    ]
